require("root.options")
require("root.keymaps")
require("root.plugins")

require("root.ui.dashbord")
require("root.ui.colorscheme")
require("root.ui.onedarkpro")
require("root.ui.feline")
require("root.ui.cokeline")
require("root.ui.indentline")

require("root.cmp")
require("root.lsp")
require("root.null-ls")
require("root.telescope")
require("root.treesitter")
require("root.autopairs")
require("root.gitsigns")
require("root.nvim-tree")
require("root.colorizer")
require("root.comment")
require("root.markdown-preview")
require("root.toggleterm")
