require("root.options")
require("root.keymaps")
require("root.plugins")
require("root.colorscheme")
require("root.cmp")
require("root.lsp")
require("root.null-ls")
require("root.telescope")
require("root.treesitter")
require("root.autopairs")
require("root.gitsigns")
require("root.nvim-tree")
require("root.colorizer")
require("root.windline")
-- require "root.lualine"
require("root.dashbord")
require("root.toggleterm")